name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -name: Check Out Repo
       uses: actions/checkout@v2

      -name: Log in to Docker Hub
       uses: docker/login-action@v1
       with:
        username: ${{ secrets.DOCKER_USERNAME }}
        username: ${{ secrets.DOCKER_PASSWORD }}

      -name: Build and Push Docker Image
       uses: docker/build-push-action@v2
       with:
        context: .
        file: ./Dockerfile
        push: true
        tags: moyezr/cashmate:latest

      -name: Verify Pushed Image
       run: docker pull moyezr/cashmate:latest